---
- name: Install httpd
  yum:
    name: httpd
    state: present

- name: Start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: yes

- name: Allow HTTP traffic on port 80
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  ignore_errors: yes

- name: Reload firewall rules
  command: firewall-cmd --reload
  ignore_errors: yes

- name: Update httpd to listen on port 80
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 80'
    line: 'Listen 80'
  notify: Restart httpd

- name: Copy Jinja2 template for index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0644'
  notify: Restart httpd

